# Generated by Django 5.0 on 2023-12-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('student_age', models.IntegerField(max_length=250)),
                ('student_rollno', models.IntegerField(max_length=250)),
                ('student_address', models.CharField(max_length=250)),
                ('student_contact', models.IntegerField(max_length=250)),
                ('student_email', models.CharField(blank=True, max_length=250, null=True)),
                ('student_standard', models.IntegerField(max_length=250)),
            ],
        ),
    ]
