# Generated by Django 5.0 on 2023-12-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='student_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='student_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='student_rollno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='student_standard',
            field=models.IntegerField(),
        ),
    ]
