# Generated by Django 5.0 on 2023-12-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_tool', '0002_alter_student_profile_student_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_english', models.IntegerField()),
                ('marks_nepali', models.IntegerField()),
                ('marks_science', models.IntegerField()),
                ('marks_math', models.IntegerField()),
                ('marks_social', models.IntegerField()),
                ('marks_eph', models.IntegerField()),
                ('marks_occupation', models.IntegerField()),
                ('marks_economics', models.IntegerField()),
                ('term', models.CharField(choices=[('first term', 'first term'), ('second term', 'second term'), ('final term', 'final term')], default='first term', max_length=250)),
                ('students', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grading_tool.student_profile')),
            ],
        ),
    ]
