# Generated by Django 5.0 on 2023-12-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_tool', '0003_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='term',
            field=models.CharField(choices=[('First Term', 'first_term'), ('Second Term', 'second_term'), ('Final Term', 'final_term')], default='first term', max_length=250),
        ),
    ]
