# Generated by Django 5.0 on 2023-12-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_tool', '0004_alter_marks_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='subject_illustrations/'),
        ),
    ]
