# Generated by Django 5.0 on 2023-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_tool', '0005_student_profile_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
