# Generated by Django 5.0 on 2024-01-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_tool', '0007_alter_marks_marks_economics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
